[package]
name = "hastyc-ast-fmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hastyc-parser = { path = "../hastyc-parser" }
hastyc-common = { path = "../hastyc-common" }